-- crear la base de datos
CREATE DATABASE IF NOT EXISTS bookstore;

-- mirar el warning
SHOW warnings;

-- crear de forma correcta las tablas book
USE bookstore;

CREATE TABLE IF NOT EXISTS books (
	book_id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT, 
	author_id INTEGER UNSIGNED,
	title VARCHAR(100) NOT NULL,
	year INTEGER UNSIGNED NOT NULL DEFAULT 1900,
	language VARCHAR(2) NOT NULL DEFAULT 'es' COMMENT 'ISO 639-1 Language',
	cover_url VARCHAR(500),
	price DOUBLE(6,2) NOT NULL DEFAULT 10.0, 
	sellable TINYINT(1) DEFAULT 1,
	description TEXT,
	
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DESCRIBE books;
DESC books;

CREATE TABLE IF NOT EXISTS authors (
	author_id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT, 
	name VARCHAR(100) NOT NULL,
	nationality VARCHAR(3),
	
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DESCRIBE authors;
DESC authors;

-- descripcion de todos las filas
SHOW FULL COLUMNS FROM books;CREATE TABLE IF NOT EXISTS clients (
	client_id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL,
	email VARCHAR(100) NOT NULL UNIQUE,
	birthdate DATETIME, -- recomendable para fechas de cumpleaños
	gender ENUM('M', 'F', 'ND') NOT NULL, -- Campo para escoger en tres opciones
	active TINYINT(1) NOT NULL DEFAULT 1, -- Se recomienda noo eliminar registros
	
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DESCRIBE clients;
DESC clients;

CREATE TABLE IF NOT EXISTS operations(
	operation_id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	book_id INTEGER UNSIGNED,
	client_id INTEGER UNSIGNED,
	status ENUM('P', 'D', 'V') NOT NULL COMMENT 'P: prestado, D: devuelto, V: vendido',
	
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	finshed TINYINT(1) NOT NULL
);



